version: '3.7'
services:
  pgsql:
    image: docker.io/postgres:latest
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgroot
      - POSTGRES_DB=pgdb
    volumes:
      - /docker/volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnt
    restart: on-failure
  app:
    image: docker.io/luiztoni/ciriguela:latest
    build:
      context: .
    container_name: ciriguela
    depends_on:
      - pgsql
    environment:
      DB_HOST: pgsql
      DB_USER: "postgres"
      DB_PASSWORD: "pgroot"
      DB_PORT: 5432
      DB_NAME: pgdb
    networks:
      - appnt
    ports:
      - "8080:8080"

networks:
  appnt:
    driver: bridge
