name: Bug report 🐞
description: Report a bug found in Ciriguela
labels: [kind/bug]

body:
  - type: markdown
    attributes:
      value: |
        ### Creating a new Bug 🐞
        🔍  Before opening a new issue please search existing issues at https://github.com/luiztoni/ciriguela/issues

        🤔  To make it easier for us to help you, please include as much useful information as possible.

        Useful Links:

          - 📄  Documentation: https://github.com/luiztoni/ciriguela/docs

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true
