name: Build and Push to Registry

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
  IMAGE_NAME: ciriguela
  TAGS: latest ${{ github.sha }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    types: [ assigned, reopened, labeled, edited ]

permissions:
  contents: read

jobs:
  build:
    name: Java ${{ matrix.java }} Maven
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project
        run: ./mvnw ${MAVEN_ARGS} clean install
      - uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Build Container Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          containerfiles: |
            ./Dockerfile

      # Push Image
      - name: Push To Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        if: github.event_name == 'push'
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: docker.io/${{ secrets.REGISTRY_USERNAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Echo outputs
        run: |
          echo "Image pushed"
          echo "${{ toJSON(steps.push-to-registry.outputs) }}"
