name: Build and Push to Registry

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
  IMAGE_NAME: ciriguela
  TAGS: latest ${{ github.sha }}
  AZURE_WEBAPP_NAME: ciriguela

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    types: [ assigned, reopened, labeled, edited ]

permissions:
  contents: read

jobs:
  build:
    name: Java ${{ matrix.java }} Maven
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Project
        run: ./mvnw ${MAVEN_ARGS} clean install

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        if: github.event_name == 'push'
        with:
          name: ciriguela
          path: '${{ github.workspace }}/target/*.jar'

      - name: Build Container Image
        uses: redhat-actions/buildah-build@v2
        if: github.event_name == 'push'
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          containerfiles: |
            ./Dockerfile

      # Push Image
      - name: Push To Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        if: github.event_name == 'push'
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: docker.io/${{ secrets.REGISTRY_USERNAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Echo outputs
        if: github.event_name == 'push'
        run: |
          echo "Image pushed"
          echo "${{ toJSON(steps.push-to-registry.outputs) }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        if: github.event_name == 'push'
        uses: actions/download-artifact@v2
        with:
          name: ciriguela

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        if: github.event_name == 'push'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ciriguela'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_APPSERVICE }}
          package: '*.jar'

      - name: Test project is running
        id: test-project
        uses: nick-invision/retry@v2.8.3
        with:
          timeout_seconds: 3
          retry_wait_seconds: 10
          max_attempts: 30
          warning_on_retry: false
          command: curl -sSfLi ${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net
